src/autores/urls.py
from django.urls import path
from .views import autores_list, autor_por_id, AutorCreateView, AutorUpdateView, autor_cambiar_estado, autores_buscar

app_name = 'autores'

urlpatterns = [
    path('', autores_list, name='autores_list'),
    path('<int:id>/', autor_por_id, name='autor_por_id'),
    # path('crear/', autor_crear, name='autor_crear'),
    path('crear/', AutorCreateView.as_view(), name='autores_crear'),
    path('actualizar/<int:pk>/', AutorUpdateView.as_view(), name='autor_actualizar'),
    path('cambiar_estado/<int:id>/', autor_cambiar_estado, name='autor_cambiar_estado'),
    path('buscar/', autores_buscar, name='buscar')
]

src/autores_prueba/urls.py
from django.urls import path
from .views import primera_vista, vista_html

app_name = 'autores_prueba'

urlpatterns = [
    path("primera/", primera_vista, name='primera_vista'),
    path("html/<str:dinamico>/<int:numero>/", vista_html, name='vista_html'),
]

src/autores_quotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from autores.views import autores_list

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', autores_list, name='autores_inicio_list'),
    path("prueba/", include('autores_prueba.urls', namespace='autores_prueba')),
    path("autores/", include('autores.urls', namespace='autores')),
    path("frases/", include('frases.urls', namespace='frases')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/frases/urls.py
from django.urls import path
from .views import FrasesListView, FrasesCreateView, FrasesUpdateView

app_name = 'frases'

urlpatterns = [
    path('', FrasesListView.as_view(), name='frases_list'),
    path('crear/', FrasesCreateView.as_view(), name='frases_crear'),
    path('edit/<int:pk>/', FrasesUpdateView.as_view(), name='frases_modificar'),
]

src/autores/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Autor(models.Model):
    """ Clase que representa a los autores de las frases """
    nombre = models.CharField(max_length=50)
    fecha_nacimiento = models.DateField()
    fecha_fallecimiento = models.DateField(null=True, blank=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)
    foto = models.ImageField(upload_to='autores_img/', default='autor_generico.png')

    def __str__(self):
        return F"{self.nombre.upper()}"
    
    def get_absolute_url(self):
        return reverse("autores:autor_por_id", kwargs={"id": self.id})
    

src/autores_prueba/models.py
from django.db import models

# Create your models here.

src/frases/models.py
from django.db import models
from autores.models import Autor
from django.urls import reverse

# Create your models here.
class Frase(models.Model):
    """Representa una frase dicha por uno de los autores"""
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE)
    contenido = models.CharField(max_length=200)
    fecha = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return F"{self.contenido}"
    

src/autores/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView
from .models import Autor
from django.urls import reverse_lazy

#Create your views here.
def autores_list(request):
        autores = Autor.objects.all()
        return render(request, 'autores/autores_list.html', {'autores': autores})

def autor_por_id(request, id):
        autor = get_object_or_404(Autor, id=id)
        return render(request, 'autores/autores_id.html', {'autor': autor})

def autor_cambiar_estado(request, id):
    autor = get_object_or_404(Autor, id=id)
    autor.activo = not(autor.activo)
    autor.save()
    return redirect("autores:autores_list")
        
class AutorCreateView(CreateView):
        model = Autor
        fields = ['nombre', 'fecha_nacimiento', 'fecha_fallecimiento', 'foto']
        template_name = 'autores/autores_edit.html'
        success_url = reverse_lazy('autores:autores_list')

class AutorUpdateView(UpdateView):
        model = Autor
        fields = ['nombre', 'fecha_nacimiento', 'fecha_fallecimiento', 'activo', 'foto']
        template_name = 'autores/autores_edit.html'
        success_url = reverse_lazy('autores:autores_list')

def autores_buscar(request):
       if request.method == 'POST':
                busqueda_autores = request.POST.get('buscar')
                resultado = Autor.objects.filter(nombre__contains=busqueda_autores)
                return render(request, 'autores/autores_list.html', {'autores': resultado})

src/autores_prueba/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def primera_vista(request):
    return HttpResponse(content="Hola desde Django!!!!")

def vista_html(request, dinamico, numero):
    return render(request, 'prueba/prueba_template.html', { 'valor':dinamico, 'anios': numero })

src/frases/views.py
from django.shortcuts import render
from django.views import generic
from .models import Frase
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy

# Create your views here.
class FrasesListView(generic.ListView):
    queryset = Frase.objects.all()
    template_name = 'frases/frases_list.html'
    context_object_name = 'lista_de_frases'

class FrasesCreateView(CreateView):
    model = Frase
    #fields = '__all__'
    fields = ['autor', 'contenido', 'fecha']
    template_name = 'frases/frases_edit.html'
    success_url = reverse_lazy('frases:frases_list')

class FrasesUpdateView(UpdateView):
    model = Frase
    fields = '__all__'
    template_name = 'frases/frases_edit.html'
    success_url = reverse_lazy('frases:frases_list')

src/templates/autores/autores_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<section class="alert alert-warning" role="alert">
    <h2 class="my-4">Crear o actualizar datos del autor</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-dark table-striped">
            <tr>
                <td>Nombre:</td>
                <td>{{form.nombre}}</td>
            </tr>
            <tr>
                <td>Fecha de Nacimiento:</td>
                <td>{{form.fecha_nacimiento}}</td>                
            </tr>
            <tr>
                <td>Fecha de Fallecimiento:</td>
                <td>{{form.fecha_fallecimiento}}</td>                
            </tr>
            <tr>
                <td>Está Activo?</td>
                <td>{{form.activo}}</td>
            </tr>
            <tr>
                <td>Foto:</td>
                <td>{{form.foto}}</td>
        </table>
        <button type="submit" class="btn btn-outline-primary m-3">Guardar</button>
        <a class="btn btn-outline-primary m-3" href="{% url 'autores:autores_list' %}"> -- Volver al listado --</a>
    </form>

    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <p> {{ error }} </p>
        {% endfor %}
    {% endfor %}
    {% endif %}
    </ul>
</section> 
{% endblock content %}

{% comment %} 
<form method="post" enctype="multipart/form-data">
     {% csrf_token %}
     {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar</button>
{% endcomment %}

src/templates/autores/autores_id.html
{% extends "base.html" %}

{% block content %}
    <h2>Datos del Autor</h2>
    <div>
        <ul>
            <li><b>Id: </b>{{autor.id}}
            <li><b>Nombre: </b>{{autor.nombre}}</li>
            <li><b>Fecha de nacimiento: </b>{{autor.fecha_nacimiento}}</li>
            <li><b>Fecha de fallecimiento: </b>{{autor.fecha_fallecimiento}}</li>
        </ul>
    </div>
    <button type="button" class="btn btn-outline-danger">
        <a href="{% url 'autores:autor_actualizar' autor.id %}"> -- Editar --</a>
    </button>
    <button type="button" class="btn btn-outline-danger">
        <a href="{% url 'autores:autores_list' %}"> -- Volver al listado --</a>
    </button>

{% endblock content %}

src/templates/autores/autores_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2 class="my-4">Listado de autores</h2>
<table class="table table-hover">
    <thead class="table-secondary">
        <tr>
            <th scope="col"></th>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Fecha Nacimiento</th>
            <th scope="col">Fecha Fallecimiento</th>
            <th scope="col">Activo</th>
            <th scope="col"></th>
            <th scope="col">Editar</th>
            <th scope="col"></th>
            <th scope="col">Frases</th>
        </tr>
    </thead>
    <tbody>
        {% for autor in autores %}
        <tr>
            <td scope="row">
                <a href="{% url 'autores:autor_por_id' autor.id %}">
                    <img src="{{ autor.foto.url }}" width="50px"/>
                </a>
            </td>
            <td>{{autor.id}}</td>
            <td>{{autor.nombre}}</td> 
            <td>{{autor.fecha_nacimiento}}</td> 
            <td>{{autor.fecha_fallecimiento}}</td>
            <td>
                {% if autor.activo %}
                    <img src="{% static 'img/verde.png' %}" alt="ACTIVO" width="30px" />
                {% else %}
                    <img src="{% static 'img/rojo.png' %}" alt="INACTIVO" width="30px" />
                {% endif %}
            </td>
            <td>
                <a href="{% url 'autores:autor_cambiar_estado' autor.pk %}">
                    {% if autor.activo %}
                      <img src="{% static 'img/encender.png' %}" alt="DESACTIVAR" width="30px" />
                    {% else %}
                      <img src="{% static 'img/apagar.png' %}" alt="ACTIVAR" width="30px" />
                    {% endif %}
                </a>
            </td>
            <td>
                <a href="{% url 'autores:autor_actualizar' autor.pk %}">
                    <img src="{% static 'img/editar.png' %}" alt="Modificar" width="30px" />
                </a>
            </td>
            <td>{{autor.frase_set.count}}</td>
            <td>
                {% for texto in autor.frase_set.all %}
                <ul>
                    <li>{{texto}}</li>
                </ul>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-outline-primary m-3" href="{% url 'autores:autores_crear' %}" role="button">Agregar autores</a>
<a class="btn btn-outline-primary m-3" href="{% url 'frases:frases_list' %}" role="button">Listar frases</a>
{% endblock content %}

src/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Super Proyecto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Proyecto Django</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Listados
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'autores:autores_list' %}">Listado de Autores</a></li>
                  <li><a class="dropdown-item" href="{% url 'frases:frases_list' %}">Listado de Frases</a></li>
                  <li><hr class="dropdown-divider"></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search" method="post" action="{% url 'autores:buscar' %}">
              {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Buscar autor" aria-label="Search" name="buscar">
              <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
          </div>
        </div>
      </nav>      
      {% block content %}
      {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/frases/frases_edit.html
{% extends "base.html" %}

{% block content %}

<h2 class="my-4">Agregar o editar frase</h2>

<form method="post">
    {% csrf_token %}
    <table class="table table-dark table-striped">
        <tr>
            <td>Contenido:</td>
            <td>{{form.contenido}}</td>
        </tr>
        <tr>
            <td>Autor:</td>
            <td>{{form.autor}}</td>                
        </tr>
        <tr>
            <td>Fecha:</td>
            <td>{{form.fecha}}</td>                
        </tr>
    </table>
    <button class="btn btn-outline-primary m-3" type="submit">Guardar</button>
    <a class="btn btn-outline-primary m-3" href="{% url 'frases:frases_list' %}" role="button">Volver</a>
</form>

{% endblock content %}

src/templates/frases/frases_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<h2 class="my-4">Listado de frases</h2>
    
<table class="table table-hover">
    <thead class="table-secondary">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Frase</th>
            <th scope="col">Autor</th>
            <th scope="col">Fecha</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        {% for frase in lista_de_frases %}
        <tr>
            <td>{{frase.id}}</td>
            <td>{{frase.contenido}}</td> 
            <td>{{frase.autor.nombre}}</td> 
            <td>{{frase.fecha}}</td> 
            <td>
                <a href="{% url 'frases:frases_modificar' frase.pk %}">
                    <img src="{% static 'img/editar.png' %}" alt="Modificar" width="30px" />
                </a>
            </td>      
        </tr>
        {% endfor %}
    </tbody>
</table>
    <a class="btn btn-outline-primary m-3" href="{% url 'frases:frases_crear' %}" role="button">Agregar frases</a>
    <a class="btn btn-outline-primary m-3" href="{% url 'autores:autores_list' %}" role="button">Inicio</a>
{% endblock content %}

src/templates/prueba/prueba_template.html
{% extends "base.html" %}

{% block content %}

Soy un heredado.

Bienvenido {{ valor }}
Tienes {{ anios }} años.

{% endblock content %}